# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/papel',
                'doc_host': 'https://nez.github.io',
                'git_url': 'https://github.com/nez/papel',
                'lib_path': 'papel'},
  'syms': { 'papel.core': { 'papel.core.dataset': ('core.html#dataset', 'papel/core.py'),
                            'papel.core.dl': ('core.html#dl', 'papel/core.py'),
                            'papel.core.papers_vector': ('core.html#papers_vector', 'papel/core.py'),
                            'papel.core.pdf': ('core.html#pdf', 'papel/core.py'),
                            'papel.core.results': ('core.html#results', 'papel/core.py'),
                            'papel.core.train_test_partition': ('core.html#train_test_partition', 'papel/core.py')}}}
