# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/papel',
                'doc_host': 'https://nez.github.io',
                'git_url': 'https://github.com/nez/papel',
                'lib_path': 'papel'},
  'syms': {'papel.core': {'papel.core.dl': ('core.html#dl', 'papel/core.py')}}}
