# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['path', 'dl']

# %% ../nbs/00_core.ipynb 2
import arxiv_dl.arxiv_dl
from pathlib import Path
path = Path("/home/nex/Downloads/ArXiv_Papers")
def dl(lista):
    for e in lista:
        arxiv_dl.arxiv_dl.main(e)
